# Site settings
title: Martin Helgesens Blog
email: martin.brusevold@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I started as a developer, currently working as a
  Operation Manager in a Norwegian company
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.martinhelgesen.no" # the base hostname & protocol for your site
twitter_username: martinhelgesen
github_username: poohbear80

# Build settings
markdown: kramdown
